pluginManagement {
	plugins {
		id 'com.android.settings' version '9.2.1' apply false
	}
	repositories {
		google {
			content {
				includeGroupByRegex("com\\.android.*")
				includeGroupByRegex("com\\.google.*")
				includeGroupByRegex("androidx.*")
			}
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
plugins {
	id 'com.android.settings'
}

android {
	execution {
		profiles {
			register("inproc") {
				r8 {
					runInSeparateProcess = false
				}
			}
			register("separate4g") {
				r8 {
					runInSeparateProcess = true
					jvmOptions += ["-Xms1024m", "-Xmx4096m", "-XX:+HeapDumpOnOutOfMemoryError"]
				}
			}
		}
		defaultProfile = "inproc"
	}
}

dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	repositories {
		google()
		mavenCentral()
		maven {
			url = uri('https://jitpack.io')
		}
	}
}


include ':app'
rootProject.name = "Miyorare"
