package org.koitharu.kotatsu.favourites.domain

const val LOCAL_FAVOURITES_CATEGORY_ID = Long.MIN_VALUE
const val LOCAL_FAVOURITES_CATEGORY_TITLE = "Lokal"
const val DOWNLOADED_FAVOURITES_CATEGORY_ID = Long.MIN_VALUE + 1L
const val DOWNLOADED_FAVOURITES_CATEGORY_TITLE = "Diunduh"

const val PRIVATE_IN_PROGRESS_CATEGORY_ID = Long.MIN_VALUE + 2L
const val PRIVATE_IN_PROGRESS_CATEGORY_TITLE = "Belum Selesai"
const val PRIVATE_COMPLETED_CATEGORY_ID = Long.MIN_VALUE + 3L
const val PRIVATE_COMPLETED_CATEGORY_TITLE = "Selesai"
